Homework 10
Andrey4281/otus_database pull request #11
Opened 2024-06-03 17:46 UTC by Andrey4281

2024-06-04 10:59 UTC, sov-87 requested changes

2024-06-04 10:59 UTC, sov-87 commented on hw10/json.sql
> +SELECT id, history FROM customer_history ch
этой таблицы нет в схеме

2024-06-04 10:59 UTC, sov-87 commented on hw10/schema.sql
> +                         `phone_number` varchar(10) UNIQUE NOT NULL,
10 символов на телефон - это очень опасно, можно будет сохранять только сильно нормализованные телефоны, причем без возможности хранения добавочных. Если на самом деле только такие надо хранить, то для них достаточно целочисленного типа.

2024-06-04 10:59 UTC, sov-87 commented on hw10/schema.sql
> +                               `card_number` varchar(20) NOT NULL COMMENT 'Credit card number',
есть карты с 19-значными номерами. если храним данные с разделителями, то для них не хватит символов

2024-06-05 15:38 UTC, Andrey4281 commented on hw10/json.sql
> +SELECT id, history FROM customer_history ch
Исправил

2024-06-05 15:40 UTC, Andrey4281 commented on hw10/schema.sql
> +                               `card_number` varchar(20) NOT NULL COMMENT 'Credit card number',
Расширил до varhcar(30)

2024-06-05 15:42 UTC, Andrey4281 commented on hw10/schema.sql
> +                         `phone_number` varchar(10) UNIQUE NOT NULL,
Расширил до varchar(20). Не думаю что стоит зацикливаться на сильно нормализованные и лучше взять диапазон шире

2024-06-06 18:55 UTC, sov-87 approved these changes

2024-06-08 13:08 UTC, merged