Hw14
Andrey4281/otus_database pull request #15
Opened 2024-06-22 09:01 UTC by Andrey4281

2024-06-23 12:00 UTC, sov-87 requested changes

2024-06-23 12:00 UTC, sov-87 commented on hw14/indexes.sql
> +SELECT id, name FROM otus.product WHERE MATCH(full_text_search) AGAINST ('IdeaPad');
не ясна цель добавления колонки для полнотекстового поиска. что в ней будет храниться? данные для полнотекстового поиска? если да, то зачем их хранить в отдельной колонке?

2024-06-23 16:26 UTC, Andrey4281 commented on hw14/indexes.sql
> +SELECT id, name FROM otus.product WHERE MATCH(full_text_search) AGAINST ('IdeaPad');
Да в full_text_search будут хранится данные для полнотекстового поиска. 
Вот соотвествующий скрипт для заполнения этой колонки
UPDATE otus.product p
    INNER JOIN manufacturer m on p.manufacturer_fk = m.id
    INNER JOIN product_category_ref prc ON prc.product_fk = p.id
    INNER JOIN product_category pc on prc.product_category_fk = pc.id
SET p.full_text_search = CONCAT(p.name, '.', cast(p.description as char(10000)), m.name, '.', pc.name);
. Те в ней у нас имя продукта, его описание, имя производителя и категория продукта, разделенные '.'. Задумка была в том чтобы наш пользователь мог использовать полнотекстовый поиск для поиска продукта как по его имени, так и по категории продукта, а также по ключевым словам в поле decription. Думал изначально не добавлять отдельную колонку под полнотекстовый поиск, и чтобы администратор или разработчик сам помимо описания продукта вносил бы категорию, имя товара и имя производителя в эту колонку. Но опять же вносить это  администратором или разработчиком - источник ошибок. Идея была в том что у нас есть description в таблице product, и name в таблице product. А при вставке будет тригер, который будет брать description в таблице product, и name в таблице product и дообагащать их именем категории и и именем производтеля и заполнять колонку для полнотекстового поиска. Посчитал также что неверно складывать все данные для полнотекстового поиска в description тк по сути это описание товара

2024-06-24 09:15 UTC, sov-87 requested changes

2024-06-24 09:15 UTC, sov-87 commented on hw14/indexes.sql
> +SELECT id, name FROM otus.product WHERE MATCH(full_text_search) AGAINST ('IdeaPad');
тогда нужно делать либо периодическую задачу (event) для заполнения этого поля, либо создавать триггеры на обновление данных в мастер-таблицах. более надежно будет решение на основе триггеров.

2024-06-26 16:50 UTC, merged