Hw16
Andrey4281/otus_database pull request #17
Opened 2024-06-30 09:47 UTC by Andrey4281

2024-06-30 19:03 UTC, sov-87 requested changes

2024-06-30 19:03 UTC, sov-87 commented on hw16/procedure.sql
> +    cardNumber varchar(20),
card_number (30)

2024-06-30 19:03 UTC, sov-87 commented on hw16/procedure.sql
> +WHILE pointer <= (LENGTH(phoneArray) - LENGTH(REPLACE(phoneArray, ',', '')) + 1)
если что-то повторяется больше одного раза, то это стоит вынести в функцию (процедуру).
кажется, задача получения таблицы со строками из строки - достаточно частая задача, чтобы один раз для этого написать функцию и потом постоянно использовать. во многих других СУБД такая функция встроена.

2024-07-01 18:19 UTC, Andrey4281 commented on hw16/procedure.sql
> +WHILE pointer <= (LENGTH(phoneArray) - LENGTH(REPLACE(phoneArray, ',', '')) + 1)
parseCustomerContactToDatabase

2024-07-16 01:59 UTC, merged