Hw9
Andrey4281/otus_database pull request #8
Opened 2024-06-01 16:24 UTC by Andrey4281

2024-06-01 18:35 UTC, sov-87 requested changes

2024-06-01 18:35 UTC, sov-87 commented on hw9/docker-compose.yaml
> +      - /home/andrey4281/mysql/data:/var/lib/mysql
1. здесь используется абсолютный путь, поэтому у меня просто так не поднимется проект.
2. изменив наименование диска `data` на абсолютный путь внутри вашей локальной системы, вы перестали использовать диск `data`. Вряд ли это то, что ожидалось получить на выходе.

2024-06-01 18:35 UTC, sov-87 commented on README.md
> +   `sysbench /usr/share/sysbench/oltp_read_write.lua --mysql-host=127.0.0.1 --mysql-port=3309 --mysql-user='root' --mysql-password='12345' --mysql-db=test --db-driver=mysql --tables=1 --table-size=10
это какой-то Ваш локальный скрипт, у меня его нет. соответственно поиграть с тестами не смогу.

2024-06-02 04:52 UTC, Andrey4281 commented on hw9/docker-compose.yaml
> +      - /home/andrey4281/mysql/data:/var/lib/mysql
поправил

2024-06-02 05:00 UTC, Andrey4281 commented on README.md
> +   `sysbench /usr/share/sysbench/oltp_read_write.lua --mysql-host=127.0.0.1 --mysql-port=3309 --mysql-user='root' --mysql-password='12345' --mysql-db=test --db-driver=mysql --tables=1 --table-size=10
Это утилита sysbench для бечмарков, нужная для выполнения задания со *. Внутрь контейнера с mysql ее не получилось установить, ставится одной командой и потом цеплятеся к докер контейнеру с mysql за счет проброшенного порта 3309
Установка sysbench
apt-get install sysbench

2024-06-02 06:22 UTC, Andrey4281 commented on README.md
> +   `sysbench /usr/share/sysbench/oltp_read_write.lua --mysql-host=127.0.0.1 --mysql-port=3309 --mysql-user='root' --mysql-password='12345' --mysql-db=test --db-driver=mysql --tables=1 --table-size=10
Добавил файл script.sh для запуска нагрузочного теста, ничего локально устанавливать не нужно. Также добавил дополнительный контейнер с этой утилитой в docker-compose

2024-06-02 09:24 UTC, sov-87 commented on README.md
> +   `innodb_buffer_pool_size=10G`'
размер буфера уже 10. каким должно быть первое значение?

2024-06-02 09:46 UTC, Andrey4281 commented on README.md
> +   `innodb_buffer_pool_size=10G`'
Первое значение было конфиг по умолчанию, там вроде около 2G

2024-06-03 17:36 UTC, merged